name: Housing Monitor

on:
  schedule:
    - cron: "*/30 * * * *" #  30 minutes
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 python-dotenv

      - name: Run monitor
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          ALERT_TO: ${{ secrets.ALERT_TO }}
          APPLICANT_SALUTATION: ${{ secrets.APPLICANT_SALUTATION }}
          APPLICANT_FIRST_NAME: ${{ secrets.APPLICANT_FIRST_NAME }}
          APPLICANT_LAST_NAME: ${{ secrets.APPLICANT_LAST_NAME }}
          APPLICANT_EMAIL: ${{ secrets.APPLICANT_EMAIL }}
          APPLICANT_PHONE: ${{ secrets.APPLICANT_PHONE }}
          APPLICANT_BIRTH_DATE: ${{ secrets.APPLICANT_BIRTH_DATE }}
          APPLICANT_NATIONALITY: ${{ secrets.APPLICANT_NATIONALITY }}
          APPLICANT_MESSAGE: ${{ secrets.APPLICANT_MESSAGE }}
          APPLICANT_UNIVERSITY: ${{ secrets.APPLICANT_UNIVERSITY }}
          APPLICANT_SEMESTER: ${{ secrets.APPLICANT_SEMESTER }}
          APPLICANT_YEAR: ${{ secrets.APPLICANT_YEAR }}
          APPLICANT_NUM_SEMESTERS: ${{ secrets.APPLICANT_NUM_SEMESTERS }}

        run: python script.py

      - name: Commit updated state
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add stwdo_state.json
          git diff --cached --quiet || git commit -m "chore: update stwdo state [skip ci]"
          git push
